package com.demo.account.db.dao.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.demo.account.db.dao.UserEntity;
import com.demo.account.db.dao.CountEntity;

import com.demo.account.db.dao.green.UserEntityDao;
import com.demo.account.db.dao.green.CountEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig countEntityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final CountEntityDao countEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        countEntityDaoConfig = daoConfigMap.get(CountEntityDao.class).clone();
        countEntityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        countEntityDao = new CountEntityDao(countEntityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(CountEntity.class, countEntityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.clearIdentityScope();
        countEntityDaoConfig.clearIdentityScope();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public CountEntityDao getCountEntityDao() {
        return countEntityDao;
    }

}
